import json

movies = json.load(open('data/movies.json'))
existing = {f"{m['title'].lower()}_{m.get('year',0)}" for m in movies}

def te(id, title, year, era, genre, director, actor, gender, imdb,
       action=False, comedy=False, romance=False, villain=False, songs=True,
       thriller=False, social=False, family=False, true_story=False, historical=False,
       bio=False, sports=False, sci_fi=False, horror=False, remake=False, franchise=False,
       pan_india=False, anti_hero=False, abroad=False, triangle=False, revenge=False, forbidden=False):
    return {
        "id": id, "title": title, "year": year, "language": "telugu", "era": era,
        "primary_genre": genre, "director": director, "lead_actor": actor, "lead_gender": gender,
        "imdb_rating": imdb,
        "has_action": action, "has_comedy": comedy, "has_romance": romance, "has_villain": villain,
        "has_songs": songs, "has_thriller_elements": thriller, "has_social_message": social,
        "is_anti_hero": anti_hero, "is_set_abroad": abroad, "has_love_triangle": triangle,
        "has_revenge_plot": revenge, "has_forbidden_love": forbidden, "is_family_film": family,
        "is_based_on_true_story": true_story, "is_biographical": bio, "is_franchise": franchise,
        "is_remake": remake, "is_sports_film": sports, "is_historical": historical,
        "is_horror": horror, "is_sci_fi": sci_fi, "is_pan_india_blockbuster": pan_india
    }

new = [
    # ── CLASSIC ERA ──────────────────────────────────────────────────────
    te("te_mayabazar","Mayabazar",1957,"classic","historical","K. V. Reddy","N. T. Rama Rao","male",9.0, historical=True, comedy=True),
    te("te_missamma","Missamma",1955,"classic","comedy","L. V. Prasad","N. T. Rama Rao","male",7.8, comedy=True, romance=True),
    te("te_patala_bhairavi","Patala Bhairavi",1951,"classic","historical","K. V. Reddy","N. T. Rama Rao","male",7.9, action=True, historical=True),
    te("te_devadasu","Devadasu",1953,"classic","drama","Vedantam Raghavaiah","Akkineni Nageswara Rao","male",7.8, romance=True, social=True),
    te("te_manchi_manasulu","Manchi Manasulu",1962,"classic","romance","Adurthi Subba Rao","Akkineni Nageswara Rao","male",7.9, romance=True),
    te("te_alluri","Alluri Seetarama Raju",1974,"classic","historical","V. Ramachandra Rao","Krishna","male",8.0, action=True, historical=True, social=True, bio=True, true_story=True),
    te("te_daana_veera","Daana Veera Soora Karna",1977,"classic","historical","N. T. Rama Rao","N. T. Rama Rao","male",8.2, action=True, historical=True),
    te("te_sagara_sangamam","Sagara Sangamam",1983,"classic","drama","K. Viswanath","Kamal Haasan","male",8.7, romance=True, social=True, bio=True),
    te("te_shiva_1989","Shiva",1989,"classic","action","Ram Gopal Varma","Nagarjuna","male",8.5, action=True, social=True, villain=True, anti_hero=True),
    te("te_swayam_krushi","Swayam Krushi",1987,"classic","drama","K. Viswanath","Chiranjeevi","male",8.0, social=True, romance=True),
    te("te_rudraveena","Rudraveena",1988,"classic","drama","K. Viswanath","Chiranjeevi","male",8.3, social=True, romance=True),
    te("te_challenge","Challenge",1984,"classic","action","Vijaya Bapineedu","Chiranjeevi","male",7.5, action=True, romance=True, villain=True),
    te("te_abhinandana","Abhinandana",1989,"classic","romance","Vamsy","Venkatesh","male",8.2, romance=True),
    te("te_kondaveeti_simham","Kondaveeti Simham",1981,"classic","action","Vijaya Bapineedu","Chiranjeevi","male",7.6, action=True, villain=True),
    te("te_samsaram_oka","Samsaram Oka Chadarangam",1987,"classic","comedy","Jandhyala","Nassar","male",8.4, comedy=True, family=True),
    te("te_nayakudu","Nayakudu",1987,"classic","action","Raghavendra Rao","Chiranjeevi","male",7.5, action=True, villain=True, romance=True),
    te("te_sankarabharanam","Sankarabharanam",1980,"classic","drama","K. Viswanath","J. V. Somayajulu","male",8.5, social=True, songs=True, bio=True),
    te("te_state_rowdy","State Rowdy",1989,"classic","action","A. Kodanda Rami Reddy","Chiranjeevi","male",7.4, action=True, social=True, villain=True),
    te("te_vijetha","Vijetha",1985,"classic","drama","Bapu","Kamal Haasan","male",8.0, social=True, family=True, songs=True),
    te("te_karthavyam","Karthavyam",1990,"90s","action","A. Kodanda Rami Reddy","Vijayashanti","female",7.6, action=True, social=True, villain=True),

    # ── 90s ──────────────────────────────────────────────────────────────
    te("te_bobbili_raja","Bobbili Raja",1990,"90s","action","Raghavendra Rao","Venkatesh","male",8.0, action=True, romance=True),
    te("te_ankusham","Ankusham",1990,"90s","action","K. Raghavendra Rao","Rajasekhar","male",7.7, action=True, social=True, villain=True),
    te("te_gang_leader","Gang Leader",1991,"90s","action","Puri Jagannadh","Chiranjeevi","male",7.5, action=True, villain=True, comedy=True),
    te("te_kondaveeti_donga","Kondaveeti Donga",1990,"90s","action","Raghavendra Rao","Chiranjeevi","male",7.4, action=True, villain=True),
    te("te_govinda_govinda","Govinda Govinda",1993,"90s","comedy","K. Raghavendra Rao","Venkatesh","male",7.6, comedy=True, romance=True),
    te("te_mutha_mestri","Mutha Mestri",1993,"90s","action","A. Kodanda Rami Reddy","Chiranjeevi","male",7.4, action=True, social=True, villain=True),
    te("te_aapattbandavudu","Aapattbandavudu",1992,"90s","action","A. Kodanda Rami Reddy","Venkatesh","male",7.5, action=True, romance=True, comedy=True),
    te("te_major_chandrakanth","Major Chandrakanth",1993,"90s","action","A. Kodanda Rami Reddy","Mohan Babu","male",7.7, action=True, social=True, villain=True),
    te("te_pedarayudu","Pedarayudu",1995,"90s","action","S. V. Krishna Reddy","Mohan Babu","male",7.6, action=True, family=True, social=True),
    te("te_hello_brother","Hello Brother",1994,"90s","comedy","E. V. V. Satyanarayana","Nagarjuna","male",7.5, comedy=True, romance=True),
    te("te_bavagaru_bagunnara","Bavagaru Bagunnara",1994,"90s","comedy","E. V. V. Satyanarayana","Chiranjeevi","male",7.8, comedy=True, romance=True),
    te("te_kshana_kshanam","Kshana Kshanam",1994,"90s","thriller","Ram Gopal Varma","Venkatesh","male",8.2, thriller=True, comedy=True, romance=True),
    te("te_master_1997","Master",1997,"90s","romance","Sreenu Vaitla","Venkatesh","male",7.3, romance=True, comedy=True),
    te("te_anthapuram","Anthapuram",1998,"90s","thriller","Ram Gopal Varma","Prakash Raj","male",7.8, thriller=True, social=True),
    te("te_annamayya","Annamayya",1997,"90s","historical","K. Raghavendra Rao","N. T. Rama Rao Jr.","male",7.9, historical=True, bio=True, true_story=True, social=True),
    te("te_krishna_1996","Krishna",1996,"90s","action","A. Kodanda Rami Reddy","Venkatesh","male",7.3, action=True, romance=True),
    te("te_allari_mogudu","Allari Mogudu",1994,"90s","comedy","G. Nageswara Reddy","Venkatesh","male",7.4, comedy=True, romance=True),
    te("te_swayamvaram","Swayamvaram",1999,"90s","romance","K. Viswanath","Venkatesh","male",7.5, romance=True, family=True),
    te("te_suswagatam","Suswagatam",1999,"90s","comedy","E. V. V. Satyanarayana","Venkatesh","male",7.4, comedy=True, romance=True, family=True),
    te("te_oke_okkadu","Oke Okkadu",2001,"2000s","action","Mani Ratnam","Arjun","male",7.4, action=True, romance=True, villain=True, remake=True),
    te("te_nee_manasu","Nee Manasu Naaku Telusu",2001,"2000s","romance","Vamsy","Tarun","male",7.3, romance=True, comedy=True),
    te("te_manmadhudu","Manmadhudu",2002,"2000s","comedy","Trivikram Srinivas","Nagarjuna","male",7.5, comedy=True, romance=True, songs=True),
    te("te_okkadu_extra","Okkadu",2003,"2000s","action","Gunasekhar","Mahesh Babu","male",7.7, action=True, romance=True, villain=True),
    te("te_naa_autograph","Naa Autograph",2004,"2000s","romance","Cheran","Ravi Teja","male",7.6, romance=True, songs=True, comedy=True),
    te("te_aadavari_matalaku","Aadavari Matalaku Ardhale Verule",2007,"2000s","comedy","Vasu Varma","Venkatesh","male",7.5, comedy=True, romance=True, songs=True),
    te("te_jai","Jai",2004,"2000s","action","Teja","Chiranjeevi","male",7.0, action=True, social=True, villain=True),
    te("te_gudumba_shankar","Gudumba Shankar",2004,"2000s","comedy","Puri Jagannadh","Pawan Kalyan","male",7.5, comedy=True, action=True, romance=True),
    te("te_arjun_2004","Arjun",2004,"2000s","action","Gunasekhar","Mahesh Babu","male",7.6, action=True, romance=True, villain=True),
    te("te_sankranthi","Sankranthi",2004,"2000s","drama","S. V. Krishna Reddy","Venkatesh","male",7.4, family=True, songs=True, comedy=True),
    te("te_nuvvostanante","Nuvvostanante Nenoddantana",2005,"2000s","romance","Prabhu Deva","Siddharth","male",7.9, romance=True, songs=True, forbidden=True),
    te("te_bangaram","Bangaram",2006,"2000s","action","Puri Jagannadh","Pawan Kalyan","male",7.3, action=True, romance=True, villain=True),
    te("te_don_telugu","Don",2007,"2000s","action","Puri Jagannadh","Nagarjuna","male",7.5, action=True, thriller=True, villain=True, remake=True),
    te("te_yamadonga_extra","Yamadonga",2007,"2000s","comedy","S. S. Rajamouli","Jr. NTR","male",7.5, comedy=True, action=True, songs=True),
    te("te_happy_days","Happy Days",2007,"2000s","comedy","Shekar Kammula","Varun Sandesh","male",8.0, comedy=True, romance=True, songs=True),
    te("te_parugu","Parugu",2008,"2000s","action","Bhaskar","Allu Arjun","male",7.6, action=True, romance=True, comedy=True),
    te("te_ready_2008","Ready",2008,"2000s","comedy","S. S. Rajamouli","Ram Pothineni","male",7.6, comedy=True, action=True, romance=True),
    te("te_wanted_2009","Wanted",2009,"2000s","action","Ram","Ram Pothineni","male",7.2, action=True, romance=True),
    te("te_darling_2010","Darling",2010,"2000s","thriller","Krishna Vamsi","Prabhas","male",7.2, thriller=True, romance=True, horror=True),
    te("te_vedam","Vedam",2010,"2000s","drama","Vasu Varma","Allu Arjun","male",8.1, social=True, action=True, villain=True),
    te("te_khaleja","Khaleja",2010,"2000s","action","Trivikram Srinivas","Mahesh Babu","male",7.2, action=True, comedy=True, romance=True),
    te("te_maryada_ramanna","Maryada Ramanna",2010,"2000s","comedy","S. S. Rajamouli","Sunil","male",7.6, comedy=True, remake=True),
    te("te_prasthanam","Prasthanam",2010,"2000s","thriller","Deva Katta","Sai Kumar","male",8.3, thriller=True, action=True, social=True, villain=True, anti_hero=True),
    te("te_brindavanam","Brindavanam",2010,"2000s","romance","Vasu Varma","N. T. Rama Rao Jr.","male",7.7, romance=True, comedy=True, songs=True, family=True),
    te("te_magadheera_2009","Magadheera",2009,"2000s","action","S. S. Rajamouli","Ram Charan","male",7.8, action=True, historical=True, romance=True, pan_india=True),
    te("te_julayi_main","Julayi",2012,"2010s","comedy","Trivikram Srinivas","Allu Arjun","male",7.6, comedy=True, action=True, thriller=True),
    te("te_businessman","Businessman",2012,"2010s","action","Puri Jagannadh","Mahesh Babu","male",7.5, action=True, villain=True, anti_hero=True, social=True),
    te("te_dookudu_main","Dookudu",2011,"2010s","comedy","Sreenu Vaitla","Mahesh Babu","male",7.5, comedy=True, action=True, romance=True),
    te("te_gabbar_singh","Gabbar Singh",2012,"2010s","comedy","Harish Shankar","Pawan Kalyan","male",7.5, comedy=True, action=True, remake=True),
    te("te_cameraman_ganga","Cameraman Gangatho Rambabu",2012,"2010s","comedy","Puri Jagannadh","Pawan Kalyan","male",7.5, comedy=True, social=True),
    te("te_seethamma_vakitlo","Seethamma Vakitlo Sirimalle Chettu",2013,"2010s","drama","Srikanth Addala","Venkatesh","male",7.5, family=True, romance=True, comedy=True),
    te("te_gopala_gopala","Gopala Gopala",2015,"2010s","comedy","Anish R. Krishnan","Venkatesh","male",7.1, comedy=True, social=True, remake=True),
    te("te_kanche","Kanche",2015,"2010s","historical","Krish Jagarlamudi","Varun Tej","male",8.2, historical=True, romance=True, true_story=True, villain=True),
    te("te_pelli_choopulu","Pelli Choopulu",2016,"2010s","comedy","Tharun Bhascker","Vijay Devarakonda","male",8.4, comedy=True, romance=True, social=True),
    te("te_bhale_bhale_magadivoy","Bhale Bhale Magadivoy",2015,"2010s","comedy","Maruthi","Nani","male",8.1, comedy=True, romance=True),
    te("te_a_aa","A..Aa",2016,"2010s","romance","Trivikram Srinivas","Nithin","male",7.9, romance=True, family=True),
    te("te_sardaar_gabbar","Sardaar Gabbar Singh",2016,"2010s","action","Bobby","Pawan Kalyan","male",7.2, action=True, comedy=True, franchise=True),
    te("te_srirastu","Srirastu Subhamastu",2016,"2010s","romance","G. Nageswara Reddy","Allu Sirish","male",7.3, romance=True, comedy=True),
    te("te_jai_lava_kusa","Jai Lava Kusa",2017,"2010s","action","Bobby","N. T. Rama Rao Jr.","male",7.9, action=True, villain=True, comedy=True),
    te("te_vunnadhi_okate","Vunnadhi Okate Zindagi",2017,"2010s","romance","Vakkantham Vamsi","Adith Arun","male",7.6, romance=True, comedy=True, triangle=True),
    te("te_nenu_sailaja","Nenu Sailaja",2016,"2010s","romance","Kishore Tirumala","Ram Pothineni","male",7.5, romance=True, comedy=True),
    te("te_shatamanam_bhavati","Shatamanam Bhavati",2017,"2010s","drama","Satish Vegesna","Sharwanand","male",8.0, family=True, romance=True),
    te("te_sye_raa","Sye Raa Narasimha Reddy",2019,"2010s","historical","Surender Reddy","Chiranjeevi","male",7.1, historical=True, action=True, true_story=True, bio=True, pan_india=True),
    te("te_mr_majnu","Mr. Majnu",2019,"2010s","romance","Venky Atluri","Akhil Akkineni","male",7.0, romance=True, comedy=True),
    te("te_gaddalakonda","Gaddalakonda Ganesh",2019,"2010s","action","Harish Shankar","Varun Tej","male",7.5, action=True, comedy=True, villain=True),
    te("te_taxiwaala_main","Taxiwaala",2018,"2010s","thriller","Rahul Sankrityan","Vijay Devarakonda","male",7.3, thriller=True, horror=True, comedy=True),
    te("te_geetha_govindam","Geetha Govindam",2018,"2010s","romance","Parasuram","Vijay Devarakonda","male",8.0, romance=True, comedy=True, songs=True),
    te("te_dear_comrade","Dear Comrade",2019,"2010s","romance","Bharat Kamma","Vijay Devarakonda","male",7.2, romance=True, social=True, songs=True),
    te("te_jersey","Jersey",2019,"2010s","drama","Gowtam Tinnanuri","Nani","male",8.5, sports=True, social=True, true_story=True, family=True),
    te("te_agent_sai","Agent Sai Srinivasa Athreya",2019,"2010s","comedy","Swaroop RSJ","Naveen Polishetty","male",8.4, comedy=True, thriller=True),
    te("te_saaho_main","Saaho",2019,"2010s","action","Sujeeth","Prabhas","male",5.3, action=True, thriller=True, abroad=True, villain=True, pan_india=True),
    te("te_arjun_reddy","Arjun Reddy",2017,"2010s","drama","Sandeep Reddy Vanga","Vijay Devarakonda","male",8.2, romance=True, social=True, anti_hero=True, villain=True),
    te("te_fidaa_main","Fidaa",2017,"2010s","romance","Sekhar Kammula","Varun Tej","male",8.0, romance=True, comedy=True, songs=True),
    te("te_maharshi_main","Maharshi",2019,"2010s","drama","Vamsi Paidipally","Mahesh Babu","male",6.8, social=True, songs=True, romance=True),
    te("te_vinaya_vidheya","Vinaya Vidheya Rama",2019,"2010s","action","Boyapati Srinu","Ram Charan","male",5.5, action=True, family=True, songs=True, villain=True),
    te("te_bharat_ane_nenu","Bharat Ane Nenu",2018,"2010s","drama","Koratala Siva","Mahesh Babu","male",7.6, action=True, social=True, romance=True, songs=True),
    te("te_rangasthalam","Rangasthalam",2018,"2010s","drama","Sukumar","Ram Charan","male",8.2, action=True, social=True, romance=True, historical=True, songs=True),
    te("te_mahanati","Mahanati",2018,"2010s","drama","Nag Ashwin","Keerthy Suresh","female",8.5, bio=True, historical=True, true_story=True, romance=True, social=True),
    te("te_race_gurram","Race Gurram",2014,"2010s","action","Surender Reddy","Allu Arjun","male",7.5, action=True, comedy=True, songs=True),
    te("te_srimanthudu","Srimanthudu",2015,"2010s","action","Koratala Siva","Mahesh Babu","male",7.3, action=True, social=True, romance=True, songs=True),
    te("te_s_o_satyamurthy","S/O Satyamurthy",2015,"2010s","drama","Trivikram Srinivas","Allu Arjun","male",7.8, family=True, songs=True, social=True, romance=True),
    te("te_nannaku_prematho","Nannaku Prematho",2016,"2010s","action","Sukumar","N. T. Rama Rao Jr.","male",7.5, action=True, romance=True, songs=True, abroad=True),
    te("te_janatha_garage","Janatha Garage",2016,"2010s","action","Koratala Siva","N. T. Rama Rao Jr.","male",7.0, action=True, social=True, songs=True, villain=True),
    te("te_khaidi_150","Khaidi No. 150",2017,"2010s","action","V. V. Vinayak","Chiranjeevi","male",7.2, action=True, social=True, songs=True, remake=True),
    te("te_katamarayudu","Katamarayudu",2017,"2010s","action","Kishore Kumar Pardasani","Pawan Kalyan","male",6.7, action=True, comedy=True, songs=True),
    te("te_dj","DJ: Duvvada Jagannadham",2017,"2010s","action","Harish Shankar","Allu Arjun","male",7.3, action=True, comedy=True, songs=True),
    te("te_oopiri","Oopiri",2016,"2010s","comedy","Vasu Varma","Nagarjuna","male",8.0, comedy=True, family=True, social=True, remake=True),
    te("te_soggade","Soggade Chinni Nayana",2016,"2010s","comedy","Kalyan Krishna","Nagarjuna","male",7.8, comedy=True, romance=True, songs=True),
    te("te_power","Power",2014,"2010s","action","K. S. Ravikumar","Ram Pothineni","male",7.0, action=True, social=True, songs=True, villain=True),
    te("te_naayak","Naayak",2013,"2010s","action","Veerabhadram","Ram Charan","male",7.1, action=True, social=True, songs=True, villain=True),
    te("te_baadshah","Baadshah",2013,"2010s","action","Sreenu Vaitla","N. T. Rama Rao Jr.","male",7.4, action=True, comedy=True, songs=True),
    te("te_attarintiki_daredi","Attarintiki Daredi",2013,"2010s","comedy","Trivikram Srinivas","Pawan Kalyan","male",8.0, comedy=True, family=True, songs=True, romance=True),
    te("te_mirchi_main","Mirchi",2013,"2010s","action","Koratala Siva","Prabhas","male",7.5, action=True, romance=True, songs=True, villain=True),
    te("te_1_nenokkadine","1: Nenokkadine",2014,"2010s","thriller","Sukumar","Mahesh Babu","male",7.5, thriller=True, action=True, romance=True, songs=True),
    te("te_baahubali_1","Baahubali: The Beginning",2015,"2010s","historical","S. S. Rajamouli","Prabhas","male",8.0, action=True, historical=True, romance=True, pan_india=True, franchise=True),
    te("te_baahubali_2","Baahubali 2: The Conclusion",2017,"2010s","historical","S. S. Rajamouli","Prabhas","male",8.2, action=True, historical=True, romance=True, pan_india=True, franchise=True, villain=True),
    te("te_temper_main","Temper",2015,"2010s","action","Puri Jagannadh","N. T. Rama Rao Jr.","male",7.7, action=True, social=True, villain=True, songs=True),
    te("te_aravindha_sametha","Aravindha Sametha Veera Raghava",2018,"2010s","action","Trivikram Srinivas","N. T. Rama Rao Jr.","male",7.4, action=True, social=True, songs=True, villain=True),
    te("te_agnyaathavaasi","Agnyaathavaasi",2018,"2010s","action","Trivikram Srinivas","Pawan Kalyan","male",5.9, action=True, villain=True, songs=True),

    # ── 2020s ────────────────────────────────────────────────────────────
    te("te_ala_vaikunthapurramuloo","Ala Vaikunthapurramuloo",2020,"2020s","action","Trivikram Srinivas","Allu Arjun","male",7.6, action=True, comedy=True, songs=True, family=True),
    te("te_bheeshma","Bheeshma",2020,"2020s","comedy","Venky Kudumula","Nithiin","male",7.1, comedy=True, romance=True, songs=True),
    te("te_sarileru","Sarileru Neekevvaru",2020,"2020s","action","Anil Ravipudi","Mahesh Babu","male",6.8, action=True, songs=True, comedy=True),
    te("te_colour_photo","Colour Photo",2020,"2020s","drama","Sandeep Raj","Suhas","male",8.5, romance=True, social=True, forbidden=True, true_story=True),
    te("te_pushpa_rise","Pushpa: The Rise",2021,"2020s","action","Sukumar","Allu Arjun","male",7.6, action=True, anti_hero=True, villain=True, songs=True, pan_india=True, true_story=True),
    te("te_shyam_singha_roy","Shyam Singha Roy",2021,"2020s","drama","Rahul Sankrityan","Nani","male",8.0, romance=True, historical=True, social=True, songs=True),
    te("te_uppena","Uppena",2021,"2020s","romance","Buchi Babu Sana","Panja Vaisshnav Tej","male",7.5, romance=True, songs=True, social=True, forbidden=True),
    te("te_vakeel_saab","Vakeel Saab",2021,"2020s","thriller","Venu Sriram","Pawan Kalyan","male",7.0, thriller=True, social=True, remake=True),
    te("te_krack","Krack",2021,"2020s","action","Gopichand Malineni","Ravi Teja","male",7.3, action=True, social=True, true_story=True, villain=True),
    te("te_akhanda","Akhanda",2021,"2020s","action","Boyapati Srinu","Balakrishna","male",7.2, action=True, songs=True, villain=True, social=True),
    te("te_rrr","RRR",2022,"2020s","historical","S. S. Rajamouli","N. T. Rama Rao Jr.","male",7.8, action=True, historical=True, true_story=True, pan_india=True),
    te("te_sita_ramam","Sita Ramam",2022,"2020s","romance","Hanu Raghavapudi","Dulquer Salmaan","male",8.4, romance=True, historical=True, songs=True),
    te("te_virata_parvam","Virata Parvam",2022,"2020s","drama","Venu Udugula","Rana Daggubati","male",7.8, romance=True, social=True, historical=True, true_story=True),
    te("te_sarkaru_vaari","Sarkaru Vaari Paata",2022,"2020s","action","Parasuram","Mahesh Babu","male",7.0, action=True, comedy=True, songs=True),
    te("te_bimbisara","Bimbisara",2022,"2020s","action","Vasantha Krishna","Kalyan Ram","male",7.3, action=True, historical=True, thriller=True),
    te("te_ante_sundaraniki","Ante Sundaraniki",2022,"2020s","comedy","Vivek Athreya","Nani","male",7.5, comedy=True, romance=True, family=True, songs=True),
    te("te_salaar","Salaar",2023,"2020s","action","Prashanth Neel","Prabhas","male",6.8, action=True, villain=True, pan_india=True, franchise=True),
    te("te_hi_nanna","Hi Nanna",2023,"2020s","romance","Shouryuv","Nani","male",7.8, romance=True, family=True, songs=True, social=True),
    te("te_waltair_veerayya","Waltair Veerayya",2023,"2020s","action","Bobby","Chiranjeevi","male",7.0, action=True, comedy=True, songs=True, social=True),
    te("te_dasara","Dasara",2023,"2020s","drama","Srikanth Odela","Nani","male",7.6, action=True, social=True, anti_hero=True, villain=True, true_story=True),
    te("te_pushpa2","Pushpa 2: The Rule",2024,"2020s","action","Sukumar","Allu Arjun","male",7.5, action=True, anti_hero=True, villain=True, songs=True, pan_india=True, franchise=True),
    te("te_lucky_baskhar","Lucky Baskhar",2024,"2020s","thriller","Venky Atluri","Dulquer Salmaan","male",8.0, thriller=True, comedy=True, social=True),
    te("te_hanu_man","Hanu Man",2024,"2020s","action","Prasanth Varma","Teja Sajja","male",7.9, action=True, sci_fi=True, songs=True, social=True),
    te("te_guntur_kaaram","Guntur Kaaram",2024,"2020s","drama","Trivikram Srinivas","Mahesh Babu","male",6.8, family=True, songs=True, social=True),
    te("te_hit2","HIT: The Second Case",2022,"2020s","thriller","Sailesh Kolanu","Adivi Sesh","male",7.4, thriller=True, action=True, villain=True, franchise=True),
    te("te_drushyam2","Drushyam 2",2021,"2020s","thriller","Jeethu Joseph","Venkatesh","male",8.4, thriller=True, villain=True, family=True, franchise=True),
    te("te_most_eligible","Most Eligible Bachelor",2021,"2020s","romance","Bommarillu Bhaskar","Akhil Akkineni","male",7.4, romance=True, comedy=True),
    te("te_major","Major",2022,"2020s","action","Sashi Kiran Tikka","Adivi Sesh","male",7.9, action=True, social=True, true_story=True, bio=True),
    te("te_karthikeya2","Karthikeya 2",2022,"2020s","action","Chandoo Mondeti","Nikhil Siddhartha","male",7.9, action=True, historical=True, thriller=True, franchise=True),
    te("te_dhamaka","Dhamaka",2022,"2020s","action","Trinadha Rao Nakkina","Ravi Teja","male",7.3, action=True, comedy=True, villain=True),
    te("te_yashoda","Yashoda",2022,"2020s","thriller","Hari-Harish","Samantha Ruth Prabhu","female",6.9, thriller=True, action=True, sci_fi=True, villain=True),
    te("te_godfather","Godfather",2022,"2020s","action","Mohan Raja","Chiranjeevi","male",6.8, action=True, villain=True, remake=True),
    te("te_aakaasam_nee_haddhu","Aakaasam Nee Haddhu Ra",2021,"2020s","drama","Sangeeth Sivan","Suriya","male",8.5, action=True, social=True, true_story=True, bio=True, remake=True),
    te("te_sye_raa_narasimha","Sye Raa Narasimha Reddy",2019,"2010s","historical","Surender Reddy","Chiranjeevi","male",7.1, historical=True, action=True, true_story=True, bio=True, pan_india=True),
    te("te_gaddalakonda","Gaddalakonda Ganesh",2019,"2010s","action","Harish Shankar","Varun Tej","male",7.5, action=True, comedy=True, villain=True),
    te("te_mr_majnu_akhil","Mr. Majnu",2019,"2010s","romance","Venky Atluri","Akhil Akkineni","male",7.0, romance=True, comedy=True),
    te("te_tuck_jagadish","Tuck Jagadish",2021,"2020s","comedy","Shiva Nirvana","Nani","male",7.2, comedy=True, family=True),
    te("te_devara","Devara",2024,"2020s","action","Koratala Siva","N. T. Rama Rao Jr.","male",7.0, action=True, historical=True, villain=True, pan_india=True),
    te("te_adipurush","Adipurush",2023,"2020s","historical","Om Raut","Prabhas","male",4.0, historical=True, action=True, pan_india=True, remake=True),
    te("te_kalki_2898","Kalki 2898 AD",2024,"2020s","action","Nag Ashwin","Prabhas","male",6.9, action=True, sci_fi=True, historical=True, pan_india=True),
    te("te_skanda","Skanda",2023,"2020s","action","Boyapati Srinu","Ram Pothineni","male",6.8, action=True, songs=True, villain=True, family=True),
    te("te_bhola_shankar","Bholaa Shankar",2023,"2020s","action","Meher Ramesh","Chiranjeevi","male",5.5, action=True, comedy=True, remake=True, family=True),
    te("te_acharya","Acharya",2022,"2020s","action","Koratala Siva","Chiranjeevi","male",5.7, action=True, social=True, villain=True),
    te("te_premalu","Premalu",2024,"2020s","comedy","Girish A. D.","Naslen","male",8.3, comedy=True, romance=True, abroad=True),
    te("te_gamanam","Gamanam",2021,"2020s","drama","Sujana Rao","Shiva Kandukuri","male",7.5, social=True, family=True, true_story=True),
    te("te_hit_2020","HIT: The First Case",2020,"2020s","thriller","Sailesh Kolanu","Vishwak Sen","male",7.7, thriller=True, action=True, villain=True, franchise=True),
    te("te_nenu_social","Nenu Social",2020,"2020s","drama","Anish R. Krishnan","Noel Sean","male",7.0, social=True, comedy=True),
    te("te_viraata_parvam","Virata Parvam",2022,"2020s","drama","Venu Udugula","Rana Daggubati","male",7.8, romance=True, social=True, historical=True, true_story=True),
]

to_add = [m for m in new if f"{m['title'].lower()}_{m['year']}" not in existing]
movies.extend(to_add)

# Dedup
seen = set()
final = []
for m in movies:
    key = f"{m['title'].lower()}_{m.get('year',0)}"
    if key not in seen:
        seen.add(key)
        final.append(m)

with open('data/movies.json', 'w') as f:
    json.dump(final, f, indent=2)

from collections import Counter
langs = Counter(m['language'] for m in final)
print(f"Added {len(to_add)} new Telugu movies (skipped {len(new)-len(to_add)} dupes)")
print(f"Counts: Tamil={langs['tamil']}, Hindi={langs['hindi']}, Telugu={langs['telugu']}, Total={len(final)}")
